### ISSUE TITLE
RestApiDelete is missing from OrthancApiHandler

### ISSUE THREAD

**Issue by kaassie** [walkIT-nl/orthanc-server-extensions#3]
* Orthanc Server Extensions version: 1.0.1
* Python version: 3.8
* Operating System: archlinux

### Description

Missing obvious OrthancApiHandler.RestApiDelete

### What I Did

handler = OrthancApiHandler()
result = handler.RestApiDelete(url)

**Comment by walcovanloon** [comment]
great first issue 👍

**Comment by kaassie** [comment]
ok, I can submit  fix for this...
